# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /mnt/home/usager/labm1507/Clean_APP/S4e_APP4_zybo_etud/S4e_Depart_etud/S4e_Depart.srcs/sources_1/bd/main_design/ip/main_design_microblaze_0_axi_intc_0_1/main_design_microblaze_0_axi_intc_0.xci
# IP: The module: 'main_design_microblaze_0_axi_intc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /mnt/home/usager/labm1507/Clean_APP/S4e_APP4_zybo_etud/S4e_Depart_etud/S4e_Depart.gen/sources_1/bd/main_design/ip/main_design_microblaze_0_axi_intc_0_1/main_design_microblaze_0_axi_intc_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'main_design_microblaze_0_axi_intc_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /mnt/home/usager/labm1507/Clean_APP/S4e_APP4_zybo_etud/S4e_Depart_etud/S4e_Depart.gen/sources_1/bd/main_design/ip/main_design_microblaze_0_axi_intc_0_1/main_design_microblaze_0_axi_intc_0_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'main_design_microblaze_0_axi_intc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /mnt/home/usager/labm1507/Clean_APP/S4e_APP4_zybo_etud/S4e_Depart_etud/S4e_Depart.gen/sources_1/bd/main_design/ip/main_design_microblaze_0_axi_intc_0_1/main_design_microblaze_0_axi_intc_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'main_design_microblaze_0_axi_intc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: /mnt/home/usager/labm1507/Clean_APP/S4e_APP4_zybo_etud/S4e_Depart_etud/S4e_Depart.srcs/sources_1/bd/main_design/ip/main_design_microblaze_0_axi_intc_0_1/main_design_microblaze_0_axi_intc_0.xci
# IP: The module: 'main_design_microblaze_0_axi_intc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /mnt/home/usager/labm1507/Clean_APP/S4e_APP4_zybo_etud/S4e_Depart_etud/S4e_Depart.gen/sources_1/bd/main_design/ip/main_design_microblaze_0_axi_intc_0_1/main_design_microblaze_0_axi_intc_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'main_design_microblaze_0_axi_intc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /mnt/home/usager/labm1507/Clean_APP/S4e_APP4_zybo_etud/S4e_Depart_etud/S4e_Depart.gen/sources_1/bd/main_design/ip/main_design_microblaze_0_axi_intc_0_1/main_design_microblaze_0_axi_intc_0_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'main_design_microblaze_0_axi_intc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /mnt/home/usager/labm1507/Clean_APP/S4e_APP4_zybo_etud/S4e_Depart_etud/S4e_Depart.gen/sources_1/bd/main_design/ip/main_design_microblaze_0_axi_intc_0_1/main_design_microblaze_0_axi_intc_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'main_design_microblaze_0_axi_intc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
