# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/main_design_constr.xdc

# Block Designs: bd/main_design/main_design.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==main_design || ORIG_REF_NAME==main_design} -quiet] -quiet

# IP: bd/main_design/ip/main_design_microblaze_0_0_1/main_design_microblaze_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==main_design_microblaze_0_0 || ORIG_REF_NAME==main_design_microblaze_0_0} -quiet] -quiet

# IP: bd/main_design/ip/main_design_mdm_0_0_1/main_design_mdm_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==main_design_mdm_0_0 || ORIG_REF_NAME==main_design_mdm_0_0} -quiet] -quiet

# IP: bd/main_design/ip/main_design_dlmb_v10_0_1/main_design_dlmb_v10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==main_design_dlmb_v10_0 || ORIG_REF_NAME==main_design_dlmb_v10_0} -quiet] -quiet

# IP: bd/main_design/ip/main_design_ilmb_v10_0_1/main_design_ilmb_v10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==main_design_ilmb_v10_0 || ORIG_REF_NAME==main_design_ilmb_v10_0} -quiet] -quiet

# IP: bd/main_design/ip/main_design_dlmb_bram_if_cntlr_0_1/main_design_dlmb_bram_if_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==main_design_dlmb_bram_if_cntlr_0 || ORIG_REF_NAME==main_design_dlmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/main_design/ip/main_design_ilmb_bram_if_cntlr_0_1/main_design_ilmb_bram_if_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==main_design_ilmb_bram_if_cntlr_0 || ORIG_REF_NAME==main_design_ilmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/main_design/ip/main_design_lmb_bram_0_1/main_design_lmb_bram_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==main_design_lmb_bram_0 || ORIG_REF_NAME==main_design_lmb_bram_0} -quiet] -quiet

# IP: bd/main_design/ip/main_design_microblaze_0_axi_periph_0_1/main_design_microblaze_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==main_design_microblaze_0_axi_periph_0 || ORIG_REF_NAME==main_design_microblaze_0_axi_periph_0} -quiet] -quiet

# IP: bd/main_design/ip/main_design_xbar_0_1/main_design_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==main_design_xbar_0 || ORIG_REF_NAME==main_design_xbar_0} -quiet] -quiet

# IP: bd/main_design/ip/main_design_microblaze_0_axi_intc_0_1/main_design_microblaze_0_axi_intc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==main_design_microblaze_0_axi_intc_0 || ORIG_REF_NAME==main_design_microblaze_0_axi_intc_0} -quiet] -quiet

# IP: bd/main_design/ip/main_design_microblaze_0_xlconcat_0_1/main_design_microblaze_0_xlconcat_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==main_design_microblaze_0_xlconcat_0 || ORIG_REF_NAME==main_design_microblaze_0_xlconcat_0} -quiet] -quiet

# IP: bd/main_design/ip/main_design_clk_wiz_1_0_1/main_design_clk_wiz_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==main_design_clk_wiz_1_0 || ORIG_REF_NAME==main_design_clk_wiz_1_0} -quiet] -quiet

# IP: bd/main_design/ip/main_design_rst_clk_wiz_1_100M_0_1/main_design_rst_clk_wiz_1_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==main_design_rst_clk_wiz_1_100M_0 || ORIG_REF_NAME==main_design_rst_clk_wiz_1_100M_0} -quiet] -quiet

# IP: bd/main_design/ip/main_design_axi_quad_spi_0_0_1/main_design_axi_quad_spi_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==main_design_axi_quad_spi_0_0 || ORIG_REF_NAME==main_design_axi_quad_spi_0_0} -quiet] -quiet

# IP: bd/main_design/ip/main_design_axi_uartlite_0_0_1/main_design_axi_uartlite_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==main_design_axi_uartlite_0_0 || ORIG_REF_NAME==main_design_axi_uartlite_0_0} -quiet] -quiet

# IP: bd/main_design/ip/main_design_axi_gpio_0_0_1/main_design_axi_gpio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==main_design_axi_gpio_0_0 || ORIG_REF_NAME==main_design_axi_gpio_0_0} -quiet] -quiet

# IP: bd/main_design/ip/main_design_myip_S4e_4reg_0_0_1/main_design_myip_S4e_4reg_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==main_design_myip_S4e_4reg_0_0 || ORIG_REF_NAME==main_design_myip_S4e_4reg_0_0} -quiet] -quiet

# IP: bd/main_design/ip/main_design_Delai_1cycle_A_0/main_design_Delai_1cycle_A_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==main_design_Delai_1cycle_A_0 || ORIG_REF_NAME==main_design_Delai_1cycle_A_0} -quiet] -quiet

# IP: bd/main_design/ip/main_design_Somme_0/main_design_Somme_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==main_design_Somme_0 || ORIG_REF_NAME==main_design_Somme_0} -quiet] -quiet

# IP: bd/main_design/ip/main_design_Delai_2cycle_0/main_design_Delai_2cycle_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==main_design_Delai_2cycle_0 || ORIG_REF_NAME==main_design_Delai_2cycle_0} -quiet] -quiet

# IP: bd/main_design/ip/main_design_processing_system7_0_0_1/main_design_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==main_design_processing_system7_0_0 || ORIG_REF_NAME==main_design_processing_system7_0_0} -quiet] -quiet

# IP: bd/main_design/ip/main_design_auto_pc_0_1/main_design_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==main_design_auto_pc_0 || ORIG_REF_NAME==main_design_auto_pc_0} -quiet] -quiet

# XDC: /mnt/home/usager/labm1507/Clean_APP/S4e_APP4_zybo_etud/S4e_Depart_etud/S4e_Depart.gen/sources_1/bd/main_design/main_design_ooc.xdc
